ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'FRIEND_ACCEPTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CHAT_MESSAGE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'MATCH_FOUND';